# Generated by Django 4.1.4 on 2022-12-19 16:49

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_size', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='booksholder',
            name='book_image',
            field=models.FileField(upload_to=homepage.models.upload_image_path),
        ),
    ]
