# Generated by Django 4.1.4 on 2023-01-18 19:21

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_colorforcover_colorfortext_papercover_paperfortext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('image', models.FileField(upload_to=homepage.models.upload_image_path)),
            ],
        ),
    ]
