# Generated by Django 4.1.4 on 2023-01-26 12:20

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_aboutteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='KijabeSerivices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.FileField(upload_to=homepage.models.upload_image_path)),
                ('service_name', models.CharField(max_length=255)),
            ],
        ),
    ]
