# Generated by Django 4.1.4 on 2023-01-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_playstorebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='playstorebook',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
