# Generated by Django 4.1.4 on 2023-02-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_playstorebook_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='playstorebook',
            name='sifuBwana',
            field=models.BooleanField(default=False),
        ),
    ]
