# Generated by Django 4.1.4 on 2023-02-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_playstorebook_sifubwana'),
    ]

    operations = [
        migrations.AddField(
            model_name='playstorebook',
            name='book_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
