# Generated by Django 4.1.4 on 2023-02-01 16:26

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_playstorebook_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='playstorebook',
            name='book_image',
            field=models.FileField(blank=True, null=True, upload_to=homepage.models.upload_image_path),
        ),
    ]
